apiVersion: apps/v1
kind: Deployment
metadata:
  name: compatibility-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: compatibility-service
  template:
    metadata:
      labels:
        app: compatibility-service
    spec:
      containers:
        - name: compatibility-service
          image: compatibility-service
          ports:
            - containerPort: 8083
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-server:8761/eureka/
---
apiVersion: v1
kind: Service
metadata:
  name: compatibility-service
spec:
  selector:
    app: compatibility-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP
