apiVersion: apps/v1
kind: Deployment
metadata:
  name: zodiac-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zodiac-service
  template:
    metadata:
      labels:
        app: zodiac-service
    spec:
      containers:
        - name: zodiac-service
          image: zodiac-service
          ports:
            - containerPort: 8082
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-server:8761/eureka/
---
apiVersion: v1
kind: Service
metadata:
  name: zodiac-service
spec:
  selector:
    app: zodiac-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP
