server:
  port: 8080

spring:
  application:
    name: apiserver
  cloud:
    config:
      enabled: true
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
